apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-service
  labels:
    app: exchange-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exchange-service
  template:
    metadata:
      labels:
        app: exchange-service
    spec:
      containers:
      - name: exchange-service
        image: localhost:6000/donkey-koin/exchange-service:latest
        livenessProbe:
          httpGet:
            path: /actuator/info
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 65
          periodSeconds: 10
          failureThreshold: 5
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
