apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-service
  labels:
    app: exchange-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exchange-service
  template:
    metadata:
      labels:
        app: exchange-service
    spec:
      containers:
      - name: exchange-service
        image: epyepy/exchange-service:latest
        ports:
        - containerPort: 8080
