apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestration
  labels:
    app: orchestration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestration
  template:
    metadata:
      labels:
        app: orchestration
    spec:
      containers:
      - name: orchestration
        image: localhost:6000/donkey-koin/orchestration:latest
        ports:
        - containerPort: 5000
